### ISSUE TITLE
Supressed error inside function call

### ISSUE THREAD

**Issue by arjendevos** [ouihealth/detox-puppeteer#21]
```
11:36:46.488 detox[35591] i Suppressed error inside function call.
  error: TypeError: driver.takeScreenshot is not a function
      at FileArtifact.<anonymous> (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox-puppeteer/src/PuppeteerScreenshotPlugin.ts:20:22)
      at Generator.next (<anonymous>)
      at /Users/arjendevos/go/src/github/half5/frontend/node_modules/tslib/tslib.js:167:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/Users/arjendevos/go/src/github/half5/frontend/node_modules/tslib/tslib.js:163:16)
      at FileArtifact.start (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox-puppeteer/build/PuppeteerScreenshotPlugin.js:17:32)
      at FileArtifact.start (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/templates/artifact/Artifact.js:52:33)
      at PuppeteerScreenshotPlugin._takeSnapshot (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js:110:20)
      at PuppeteerScreenshotPlugin._takeAutomaticSnapshot (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js:103:20)
      at PuppeteerScreenshotPlugin.onTestStart (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/templates/plugin/TwoSnapshotsPerTestPlugin.js:41:16)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at /Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/ArtifactsManager.js:224:11
      at async Promise.all (index 0)
      at ArtifactsManager._callPlugins (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/ArtifactsManager.js:222:7)
      at ArtifactsManager.onTestStart (/Users/arjendevos/go/src/github/half5/frontend/node_modules/detox/src/artifacts/ArtifactsManager.js:187:5)
```

I don't call this function, so i've no idea what is going on.

**Comment by awinograd** [comment]
Hi @arjendevos 

Thanks for the report. Unfortunately I won't be able to figure out what's going on without a reproducible example. The takeScreenshot function is called automatically if you've [configured detox to take save screenshots of your tests](https://wix.github.io/Detox/docs/guide/taking-screenshots/#artifacts-management)
