### ISSUE TITLE
detox-puppeteer is not working with all detox 20 versions 

### ISSUE THREAD

**Issue by MetodievIvaylo** [ouihealth/detox-puppeteer#23]
I have tried to run my web app with detox-puppeteer but the browser just did not launch. After a couple of days I updated the detox version from `"detox": "20.14.2-smoke.0`" to the version in your project `"detox": "^20.11.0"` and the application started. 

I also updated to the current `last detox version 20.18.1` and still was not able to start the browser.

Here is the error:
```
    TimeoutError: Navigation timeout of 30000 ms exceeded

      at new Deferred (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/util/Deferred.ts:68:28)
      at Function.create (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/util/Deferred.ts:24:12)
      at new LifecycleWatcher (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/cdp/LifecycleWatcher.ts:170:42)
      at CdpFrame.goto (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/cdp/Frame.ts:138:21)
      at CdpFrame.<anonymous> (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/util/decorators.ts:61:21)
      at CdpPage.goto (../../node_modules/.pnpm/puppeteer-core@21.9.0/node_modules/puppeteer-core/src/api/Page.ts:1553:35)
      at PuppeteerRuntimeDriver.<anonymous> (../../node_modules/.pnpm/detox-puppeteer@6.0.1_detox@20.11.0/node_modules/detox-puppeteer/src/PuppeteerDriver.ts:1103:19)
      at fulfilled (../../node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:166:62)
```

**Comment by awinograd** [comment]
Hi @MetodievIvaylo,

It's hard to know exactly what may be happening in your use case without seeing more config/code. I would double check that your project is serving the web version of your app at the host url configured in `binaryPath`
